# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Minji Jeong's Portfolio
# Description of the Site
description: Back-end Developer - Experiences of Commerce, POS, Retail Business Industry 
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/main_top_img.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: minji279@gmail.com
facebook_username: /
twitter_username: /
instagram_username: find.me.forward
linkedin_username: minji-jeong-173235170
github_username:  minjijeong
youtube_channel_id: UCMeFZUvoLK4tSdvUxmUfKTA
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus 
# 블로그 댓글 추가 방법 https://devinlife.com/howto%20github%20pages/blog-disqus/
# https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
disqus-shortname: minjijeong-github-io

# Name of the Author
author-name: Minji Jeong
# URL for the Image of the Author //file:///Users/minjijeong/Pictures/Photos%20Library.photoslibrary/resources/renders/5/52D40759-912B-4698-B46E-C96F141D8AC6_1_201_a.jpeg
author-image: /assets/images/profile_imgs.jpeg
# 60 Words About the Author
#author-about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
author-about: Java, Spring, oracle, mysql 기반으로 한 back-end 개발자 입니다. <br> 업무 효율성에 대해 생각하고, 그를 위해 의사소통 및 문서, 가이드 작성을 중요하게 생각합니다.
author-about-short : Java, Spring, oracle, mysql 기반으로 한 back-end 개발자 ...
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/minjijeong

# I use Notion App instead of blog for Tech Study 
author-tech-url: https://stirring-frown-8f3.notion.site/2d6b342661844f8eb3a09303b3b4a9e9  

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
